# Kubernetes LDAP integration
# https://example.atlassian.net/browse/DOPS-3531
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-oidc-proxy-repo
  namespace: flux-system
spec:
  url: https://github.com/jetstack/kube-oidc-proxy
  interval: 10m
  ref:
    branch: 'v0.3.0'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-oidc-proxy
  namespace: flux-system
spec:
  # The interval at which to reconcile the Helm release
  interval: 10m
  releaseName: kube-oidc-proxy
  targetNamespace: kube-system
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./deploy/charts/kube-oidc-proxy
      # The reference to the GitRepository
      sourceRef:
        kind: HelmRepository
        name: kube-oidc-proxy-repo
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: default-cluster-values
  values:
    # Exposing through ingress with precreated TLS certs.
    tls:
      secretName: star-tech-example-net
    service:
      type: LoadBalancer
      annotations:
        cloud.google.com/load-balancer-type: Internal
        networking.gke.io/internal-load-balancer-allow-global-access: "true"
    # oidc config
    oidc:
      issuerUrl: 'https://dex.tech.example.net'
      usernameClaim: email
      groupsClaim: groups
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-kube-oidc-proxy
  namespace: kube-system
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/0
    ## GCE Health Checks
    - ipBlock:
        cidr: 130.211.0.0/22
    - ipBlock:
        cidr: 35.191.0.0/16
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-oidc-proxy
  policyTypes:
  - Ingress
