# Kubernetes LDAP integration
# https://example.atlassian.net/browse/DOPS-3531
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-oidc-proxy
  namespace: flux
spec:
  releaseName: kube-oidc-proxy
  targetNamespace: kube-system
  chart:
    git: "https://github.com/jetstack/kube-oidc-proxy"
    path: "deploy/charts/kube-oidc-proxy"
    ref: "v0.3.0"
    name: "kube-oidc-proxy"
  valuesFrom:
  - configMapKeyRef:
      name: default-cluster-values
  values:
    # Exposing through ingress with precreated TLS certs.
    tls:
      secretName: star-tech-example-net
    service:
      type: LoadBalancer
      annotations:
        cloud.google.com/load-balancer-type: Internal
        networking.gke.io/internal-load-balancer-allow-global-access: "true"
    # oidc config
    oidc:
      issuerUrl: 'https://dex.tech.example.net'
      usernameClaim: email
      groupsClaim: groups

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-kube-oidc-proxy
  namespace: kube-system
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/0
    ## GCE Health Checks
    - ipBlock:
        cidr: 130.211.0.0/22
    - ipBlock:
        cidr: 35.191.0.0/16
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-oidc-proxy
  policyTypes:
  - Ingress
